spring.application.name=foodiesapi
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies

#aws s3 configuration
#aws.access.key=${AWS_ACCESS_KEY}
#aws.secret.key=${AWS_SECRET_KEY}
#aws.region=${AWS_REGION}
#aws.s3.bucketname=${AWS_BUCKET_NAME}

# AWS dummy config (for local development)
aws.access.key=dummy-access-key
aws.secret.key=dummy-secret-key
aws.region=ap-south-1
aws.s3.bucketname=dummy-bucket-name


#jwt.secret.key=${JWT_SECRET}
jwt.secret.key=Tgud4emPAmPzX6t3GroNRugnM8IniMRVSzohwyQhq9V3HWzhvd3kS9MLtDl5KqwR



#razorpay configuration
#razorpay_key=${RAZORPAY_KEY}
#razorpay_secret=${RAZORPAY_SECRET}

razorpay_key=dfsdfsdfwFSF
razorpay_secret=DSFADSBVBSgfhgdhsf

#Local storage path for storing images
file.upload-dir=F:/code/NewProjects/food-delivery-application/online-food-delivery-project/Uploads